"""PPS GAME — admin-only team knowledge quiz (2025 performance review facts)."""

PPS_GAME_META = {
    'title': 'PPS GAME',
    'subtitle': 'How well do you know your team?',
    'description': '30 questions drawn from 2025 performance reviews. Admin eyes only.',
    'pass_score': 20,
    'expert_score': 26,
}

PPS_GAME_QUESTIONS = [
    {
        'id': 'tony_sales',
        'category': 'Tony',
        'question': 'What did Tony report for 2025 sales volume and gross margin?',
        'options': ['~$1.5M at 18% GM', '~$2M at ~22% GM', '~$2.5M at 25% GM', '~$3M at 20% GM'],
        'correct': 1,
        'explanation': 'Tony finished ~$2M in sales with ~22% gross margin while balancing VP Sales and production.',
    },
    {
        'id': 'tony_score',
        'category': 'Tony',
        'question': "What was Tony's overall 2025 review score?",
        'options': ['2.88 — Below Expectations', '3.06 — Meets Expectations', '3.50 — Exceeds Expectations', '3.88 — Exceeds Expectations'],
        'correct': 1,
        'explanation': 'Anthony V. Cumella scored 3.06 — Meets Expectations.',
    },
    {
        'id': 'tony_closeouts',
        'category': 'Tony',
        'question': 'Which closeout issue did the supervisor cite for Tony (60+ days past due)?',
        'options': ['Indian Creek 5410 & The Verge', 'Chestnut Park & Tall Timber', 'Queens Tower & Pure Couture', 'Morgan pool fences & McAlpin'],
        'correct': 1,
        'explanation': 'Supervisor noted Chestnut Park and Tall Timber staying open 60+ days past due due to punch-list/invoice timing.',
    },
    {
        'id': 'tony_handoff',
        'category': 'Tony',
        'question': 'When Tony hands jobs to PMs, what communication theme did the supervisor flag?',
        'options': ['Too many Monday.com updates', 'Disconnect with PMs — "less is more"', 'Over-delegating to Jordan', 'Avoiding client follow-up'],
        'correct': 1,
        'explanation': 'Handoffs to Derek, Phil, and/or James show a disconnect; feedback was to be more concise.',
    },
    {
        'id': 'jordan_volume',
        'category': 'Jordan',
        'question': 'How many jobs did Jordan lead-PM in 2025, and roughly what dollar volume?',
        'options': ['200 jobs / ~$2.5M', '308 jobs / ~$4M', '150 jobs / ~$1.8M', '400 jobs / ~$5M'],
        'correct': 1,
        'explanation': 'Jordan managed 308 total jobs as lead PM and nearly $4M in job value.',
    },
    {
        'id': 'jordan_score',
        'category': 'Jordan',
        'question': "What was Jordan's overall 2025 review score?",
        'options': ['3.06 — Meets', '3.25 — Meets', '3.81 — Exceeds', '3.88 — Exceeds'],
        'correct': 3,
        'explanation': 'Jordan S. Allen scored 3.88 — Exceeds Expectations.',
    },
    {
        'id': 'jordan_comm',
        'category': 'Jordan',
        'question': 'Jordan self-rated Communication at 3. What did the supervisor rate it?',
        'options': ['5 — Exceptional', '4 — Exceeds', '3 — Meets', '2 — Needs Improvement'],
        'correct': 3,
        'explanation': 'Supervisor rated listening/communication at 2 — biggest improvement area.',
    },
    {
        'id': 'jordan_fence',
        'category': 'Jordan',
        'question': 'What was the Morgan Properties pool-fence material mistake?',
        'options': ['Wrong fence height (4 ft vs 6 ft)', '¾" pickets instead of 1" spec', 'Galvanized instead of powder coat', 'Posts set in concrete too shallow'],
        'correct': 1,
        'explanation': 'Fence pickets arrived at ¾" instead of the 1" size in scope — a quarter-inch caused major problems.',
    },
    {
        'id': 'jordan_bonus',
        'category': 'Jordan',
        'question': 'Which quarterly bonus goal did Jordan hit every quarter since it started?',
        'options': ['15 Monday updates/week', '$100K+ margin on PM jobs', '$1M personal sales', 'Zero client callbacks'],
        'correct': 1,
        'explanation': 'Jordan hit every quarterly margin bonus ($100K+ margin on jobs he PMed).',
    },
    {
        'id': 'phil_score',
        'category': 'Phil',
        'question': "What was Phil's overall 2025 review score?",
        'options': ['3.06 — Meets', '3.25 — Meets', '3.81 — Exceeds', '3.88 — Exceeds'],
        'correct': 2,
        'explanation': 'Philip M. Miller scored 3.81 — Exceeds Expectations.',
    },
    {
        'id': 'phil_gap',
        'category': 'Phil',
        'question': 'Phil self-rated Work Quality at 5. What did the supervisor rate?',
        'options': ['5 — Exceptional', '4 — Exceeds', '3 — Meets', '2 — Needs Improvement'],
        'correct': 2,
        'explanation': 'Supervisor rated quality at 3 — Meets, citing margin/risk and project mix concerns.',
    },
    {
        'id': 'phil_comm',
        'category': 'Phil',
        'question': 'Which project did the supervisor tie to Phil\'s communication score of 2?',
        'options': ['Bridges elevator', 'Pure Couture', 'BOPC apartments', 'Vantage Point West'],
        'correct': 1,
        'explanation': 'Pure Couture change orders communicated too late; Monday updates also flagged.',
    },
    {
        'id': 'adam_score',
        'category': 'Adam',
        'question': "What was Adam's overall 2025 review score?",
        'options': ['3.06 — Meets', '3.56 — Exceeds', '3.81 — Exceeds', '3.88 — Exceeds'],
        'correct': 3,
        'explanation': 'Adam Cupito scored 3.88 — Exceeds Expectations.',
    },
    {
        'id': 'adam_teamwork',
        'category': 'Adam',
        'question': 'Adam and supervisor both rated Teamwork highly — what did the supervisor give?',
        'options': ['3 — Meets', '4 — Exceeds', '5 — Exceptional', 'Not rated'],
        'correct': 2,
        'explanation': 'Supervisor gave Adam a 5 on Teamwork — key contributor through collaboration.',
    },
    {
        'id': 'adam_tools',
        'category': 'Adam',
        'question': 'What improvement area did the supervisor name for Adam?',
        'options': ['More travel to new markets', 'Excel and internal tracking tools', 'Fewer group meetings', 'Monday.com photo uploads'],
        'correct': 1,
        'explanation': 'Supervisor: improve Excel/tools for opportunity tracking; build sub relationships.',
    },
    {
        'id': 'andy_sales',
        'category': 'Andy',
        'question': 'What were Andy\'s reported 2025 sales and margin percentage (~10 effective months)?',
        'options': ['$750K sales / 22% margin', '$1.07M sales / 29.6% margin', '$1.5M sales / 30% margin', '$900K sales / 25% margin'],
        'correct': 1,
        'explanation': 'Andy: $1.07M sales (above ~$750K budget), $317K margin, 29.6% GM in ~10 months.',
    },
    {
        'id': 'andy_incomplete',
        'category': 'Andy',
        'question': "What is missing from Andy's 2025 review PDF?",
        'options': ['Employee extended responses', 'All supervisor ratings & summary Qs', 'Role-specific sales questions', 'Core skill employee ratings'],
        'correct': 1,
        'explanation': 'Andy\'s PDF has employee ratings only — no supervisor core ratings and blank supervisor Q1–3.',
    },
    {
        'id': 'andy_partner',
        'category': 'Andy',
        'question': 'Which PM did Andy lean on heavily in year one, especially early on?',
        'options': ['Derek Ramsey', 'Ben Ramsey', 'Jordan Allen', 'James Boling'],
        'correct': 1,
        'explanation': 'Andy leaned on Ben for pricing/process; they teamed on Indian Creek and production.',
    },
    {
        'id': 'james_tenure',
        'category': 'James',
        'question': 'How did James describe his 2025 tenure and primary role?',
        'options': ['Full year as lead PM', '~7 months, mostly floater/support', 'Cincinnati-only dedicated PM', 'Columbus market launch PM'],
        'correct': 1,
        'explanation': 'James had ~7 months at PPS, much of it as a floater (Belle Meadows, Chestnut Park, support PM).',
    },
    {
        'id': 'james_incomplete',
        'category': 'James',
        'question': "What is largely blank in James's supervisor section?",
        'options': ['Employee core ratings only', 'Most supervisor comments & all 3 summary Qs', 'Role-specific PM questions', 'Extended response answers'],
        'correct': 1,
        'explanation': 'Many supervisor core comments are "." and all three supervisor summary questions are empty.',
    },
    {
        'id': 'derek_gap',
        'category': 'Derek',
        'question': 'Derek self-rated Initiative at 5. What did the supervisor rate?',
        'options': ['5 — Exceptional', '4 — Exceeds', '3 — Meets', '2 — Needs Improvement'],
        'correct': 3,
        'explanation': 'Supervisor rated Initiative at 2 — needs stakeholders to follow up on assigned tasks.',
    },
    {
        'id': 'derek_queens',
        'category': 'Derek',
        'question': 'Which job did the supervisor call a "microcosm" of Derek\'s struggles?',
        'options': ['Tall Timbers', 'City Homes', 'Queens Tower', 'McAlpin rooftop patio'],
        'correct': 2,
        'explanation': 'Queens Tower — waited weeks on Phil when input wasn\'t necessary; problem-solving rated 2.',
    },
    {
        'id': 'ben_monday',
        'category': 'Ben',
        'question': 'How many Monday.com updates per week did Ben report averaging (target was 15)?',
        'options': ['15–20', '20–25', '30–40', '50+'],
        'correct': 2,
        'explanation': 'Ben averaged 30–40 updates/week vs the 15/week KPI target.',
    },
    {
        'id': 'ben_lesson',
        'category': 'Ben',
        'question': 'What margin lesson did Ben take from Whispering Woods siding?',
        'options': ['Hire more subs upfront', 'Structured pre-pro & existing-conditions docs', 'Stop using Monday.com', 'Delegate margin checks to sales'],
        'correct': 1,
        'explanation': 'Lack of pre-pro meeting and pre-existing damage documentation hurt margins; now uses checklists.',
    },
    {
        'id': 'stephanie_score',
        'category': 'Stephanie',
        'question': "What was Stephanie's overall 2025 review score?",
        'options': ['3.06 — Meets', '3.25 — Meets', '3.56 — Exceeds', '3.88 — Exceeds'],
        'correct': 2,
        'explanation': 'Stephanie E.J. Whetstone scored 3.56 — Exceeds Expectations.',
    },
    {
        'id': 'stephanie_leave',
        'category': 'Stephanie',
        'question': 'During Stephanie\'s maternity leave, what did the supervisor realize doing ~10% of her job?',
        'options': ['The role could be fully automated', 'How much she carries — "wake up call"', 'Monday.com should be outsourced', 'QB could replace the position'],
        'correct': 1,
        'explanation': 'Thomas covering 10% of her role during leave was a wake-up to how much Stephanie does.',
    },
    {
        'id': 'stephanie_risk',
        'category': 'Stephanie',
        'question': 'What process risk did Stephanie flag wanting to brainstorm with Everett?',
        'options': ['Duplicate expense entries', 'Double pay requests', 'Lost sub W-9s', 'Invoice approval delays'],
        'correct': 1,
        'explanation': 'She wants a solution for double pay requests not caught by PO/line-item checks.',
    },
    {
        'id': 'exceeds_who',
        'category': 'Team',
        'question': 'Which four people scored "Exceeds" on completed 2025 reviews (3.56+)?',
        'options': ['Tony, Andy, Derek, James', 'Jordan, Phil, Adam, Stephanie', 'Ben, James, Tony, Andy', 'Jordan, Adam, Ben, Stephanie'],
        'correct': 1,
        'explanation': 'Jordan (3.88), Phil (3.81), Adam (3.88), Stephanie (3.56) — all Exceeds on complete reviews.',
    },
    {
        'id': 'incomplete_who',
        'category': 'Team',
        'question': 'Which reviews need the most supervisor content filled before delivery?',
        'options': ['Jordan & Phil only', 'Andy & James (plus partial Derek/Ben)', 'Tony & Stephanie', 'Adam & Ben only'],
        'correct': 1,
        'explanation': 'Andy (no sup ratings), James (blank sup section), Derek Q1–2 and Ben Q1–3 still empty.',
    },
    {
        'id': 'travel_pm',
        'category': 'Team',
        'question': 'Who raised sustainability concerns about out-of-state travel and suggested a travel PM hire?',
        'options': ['Tony Cumella', 'Derek Ramsey', 'Jordan Allen', 'Phil Miller'],
        'correct': 2,
        'explanation': 'Jordan is out of state most weeks; discussed hiring a dedicated travel PM role.',
    },
]