"""Training curriculum overlay — Phase 2 of the in-app training editor.

The curriculum lives in ``psc_training_data.py`` and ``pm_training_data.py`` and
stays there. This module holds only what leadership has *changed* since: edits
to existing items, and items they have added. At read time the two are merged.

Why an overlay rather than moving 2,900 lines of curriculum into the database:
the authored content is reviewable in version control, diffable, and survives a
database restore. Only the deltas need to be editable at runtime, and there will
not be many of them — Thomas, 2026-08-23: edits happen "in waves", not daily.

**How a change reaches people** (Thomas's model, same day):

    A trainee's programme is fixed when they start. Items added later still
    reach them, as a section at the end rather than by reopening a week they
    already closed. New hires get those same items in their proper week.

So an addition is placed in-line for anyone who enrolled *after* it published,
and collected into a separate "added since you started" bucket for anyone who
enrolled before. That bucket is deliberately NOT counted toward week
percentages or the overall figure — see ``apply``. A signed-off week must stay
signed off permanently; that is the property this whole design protects.

Text edits are different and flow through to everyone as soon as they publish.
An edit keeps the item's ID, so no progress row moves, and deferring edits would
leave people reading wording that has since been corrected.

**IDs.** Added items get a minted ID containing ``_x_`` — see ``mint_item_id``.
Nothing generated by the base curriculum can collide with that shape, and the
marker makes an overlay item obvious in a progress table. Base item IDs are
frozen; see tests/test_training_item_ids.py for why that matters.
"""

from __future__ import annotations

import json
import secrets
from datetime import datetime

MODULES = ('psc', 'pm')

# Containers an item can live in, per scope. Anything not listed is not editable
# in Phase 3, which is deliberate — weeks and the three standalone sections are
# where the content people actually maintain lives.
WEEK_CONTAINERS = ('videos', 'shadowing', 'additional', 'pps_focus')
SECTION_CONTAINERS = {
    'core_values': ('sections', 'activities'),
    'sales_training': ('modules', 'items'),
    'company_operations': ('modules', 'items'),
}

# Overlay reads are cached per worker for this long. Publishing clears the cache
# in the worker that served the request; the other worker picks the change up
# within the window. That is the honest trade for not reading two tables on
# every dashboard load, and a minute of staleness is invisible for something
# edited a few times a year.
CACHE_TTL_SECONDS = 60

_cache = {'at': None, 'data': None}


def init_tables(cur):
    cur.execute('''
        CREATE TABLE IF NOT EXISTS training_overlay_items (
            id SERIAL PRIMARY KEY,
            module VARCHAR(8) NOT NULL,
            item_id VARCHAR(100) NOT NULL,
            target JSONB NOT NULL,
            payload JSONB NOT NULL,
            sort_order INTEGER DEFAULT 0,
            created_by VARCHAR(100),
            created_at TIMESTAMP DEFAULT NOW(),
            published_at TIMESTAMP,
            active BOOLEAN DEFAULT TRUE,
            UNIQUE (module, item_id)
        )
    ''')
    cur.execute('''
        CREATE TABLE IF NOT EXISTS training_overlay_edits (
            id SERIAL PRIMARY KEY,
            module VARCHAR(8) NOT NULL,
            item_id VARCHAR(100) NOT NULL,
            fields JSONB NOT NULL DEFAULT '{}'::jsonb,
            hidden BOOLEAN DEFAULT FALSE,
            updated_by VARCHAR(100),
            updated_at TIMESTAMP DEFAULT NOW(),
            published_at TIMESTAMP,
            UNIQUE (module, item_id)
        )
    ''')
    for stmt in (
        "CREATE INDEX IF NOT EXISTS idx_overlay_items_module ON training_overlay_items(module)",
        "CREATE INDEX IF NOT EXISTS idx_overlay_edits_module ON training_overlay_edits(module)",
    ):
        try:
            cur.execute(stmt)
        except Exception:
            pass


def mint_item_id(module, hint='item', rand=None):
    """A stable ID for a newly added item.

    ``_x_`` is the marker: no base ID can contain it, because every generated
    base ID is ``w{n}_{kind}_{index}`` or a hand-written slug, and the frozen
    list is asserted in tests. Without a marker there is no way to tell an
    overlay item from an authored one when reading a progress row.

    The hint is cosmetic — it makes the table readable — and is truncated hard
    because ``item_id`` is VARCHAR(100) and progress rows key on it.
    """
    slug = ''.join(c if c.isalnum() else '_' for c in (hint or 'item').lower())[:24].strip('_')
    token = rand() if rand else secrets.token_hex(4)
    return f'{module}_x_{slug or "item"}_{token}'


def _as_dict(value):
    """psycopg2 returns jsonb as dict OR str depending on version and cursor.

    Same trap as `system_state._json_object` — see the note in CLAUDE.md.
    """
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
            return parsed if isinstance(parsed, dict) else {}
        except Exception:
            return {}
    return {}


def load_overlay(get_db, now=None, use_cache=True):
    """Published overlay rows for both modules.

    Returns ``{'psc': {'edits': {...}, 'items': [...]}, 'pm': {...}}``.
    Drafts — rows with no ``published_at`` — are excluded here on purpose: this
    is the trainee-facing read. The editor reads drafts separately.

    Returns empty structures on any database trouble rather than raising. A
    training page that 500s because an optional overlay is unreachable is worse
    than one that shows the authored curriculum, which is exactly what the
    empty case produces.
    """
    now = now or datetime.utcnow()
    if use_cache and _cache['at'] and (now - _cache['at']).total_seconds() < CACHE_TTL_SECONDS:
        return _cache['data']

    blank = {m: {'edits': {}, 'items': []} for m in MODULES}
    conn = None
    try:
        conn = get_db()
        if not conn:
            return blank
        cur = conn.cursor()
        cur.execute(
            'SELECT module, item_id, fields, hidden FROM training_overlay_edits '
            'WHERE published_at IS NOT NULL'
        )
        for module, item_id, fields, hidden in cur.fetchall():
            if module in blank:
                blank[module]['edits'][item_id] = {
                    'fields': _as_dict(fields),
                    'hidden': bool(hidden),
                }
        cur.execute(
            'SELECT module, item_id, target, payload, sort_order, published_at '
            'FROM training_overlay_items '
            'WHERE published_at IS NOT NULL AND active = TRUE '
            'ORDER BY sort_order, id'
        )
        for module, item_id, target, payload, sort_order, published_at in cur.fetchall():
            if module in blank:
                blank[module]['items'].append({
                    'item_id': item_id,
                    'target': _as_dict(target),
                    'payload': _as_dict(payload),
                    'sort_order': sort_order or 0,
                    'published_at': published_at,
                })
        cur.close()
    except Exception as e:
        print(f'training overlay read error: {e}')
        return {m: {'edits': {}, 'items': []} for m in MODULES}
    finally:
        if conn:
            try:
                conn.close()
            except Exception:
                pass

    if use_cache:
        _cache['at'], _cache['data'] = now, blank
    return blank


def clear_cache():
    """Called on publish. See CACHE_TTL_SECONDS for the other worker."""
    _cache['at'], _cache['data'] = None, None


# ── Applying the overlay ────────────────────────────────────────────────────

def _week_containers(week):
    for name in WEEK_CONTAINERS:
        if isinstance(week.get(name), list):
            yield name, week[name]


def _all_containers(curriculum):
    """Yield (container_list,) for every list of items in the curriculum.

    Kept in one place so `apply` and any future validation walk the structure
    identically — the shapes differ per section and drifting walkers is how a
    hidden item ends up hidden in one view and visible in another.
    """
    onboarding, weeks, core_values, sales_training, company_operations = curriculum
    for week in [onboarding] + list(weeks):
        for _name, lst in _week_containers(week):
            yield lst
    for section in (core_values or {}).get('sections', []) or []:
        if isinstance(section.get('activities'), list):
            yield section['activities']
    for blob in (sales_training, company_operations):
        for module in (blob or {}).get('modules', []) or []:
            if isinstance(module.get('items'), list):
                yield module['items']


def _target_container(curriculum, target):
    """Resolve an addition's target to the actual list it belongs in.

    Returns None when the target does not exist — a week that was removed, a
    module renamed. The item is then treated as unplaceable and surfaced in the
    appended bucket rather than dropped, so an addition can never silently
    vanish because someone edited the base file.
    """
    onboarding, weeks, core_values, sales_training, company_operations = curriculum
    kind = target.get('kind')
    if kind == 'week':
        want = target.get('week')
        container = target.get('container')
        if container not in WEEK_CONTAINERS:
            return None
        for week in [onboarding] + list(weeks):
            if week.get('week') == want:
                if not isinstance(week.get(container), list):
                    week[container] = []
                return week[container]
        return None
    if kind == 'section':
        section_name = target.get('section')
        spec = SECTION_CONTAINERS.get(section_name)
        if not spec:
            return None
        group_key, item_key = spec
        blob = {'core_values': core_values, 'sales_training': sales_training,
                'company_operations': company_operations}.get(section_name)
        for group in (blob or {}).get(group_key, []) or []:
            if group.get('id') == target.get('group_id'):
                if not isinstance(group.get(item_key), list):
                    group[item_key] = []
                return group[item_key]
        return None
    return None


def apply(curriculum, overlay_for_module, enrolled_at=None):
    """Merge the overlay into a curriculum the caller owns.

    ``curriculum`` MUST be a private copy — pass the result of
    ``get_training_curriculum()``, never ``read_curriculum()``. This function
    edits in place, and writing into the shared cache would leak one trainee's
    view into every later request on the worker.

    ``enrolled_at`` is when this person started. ``None`` means "show the
    programme as authored today", which is what an unenrolled viewer, a manager
    previewing, and the editor itself all want.

    Returns ``(curriculum, added_since)`` where ``added_since`` is the list of
    items published after this trainee enrolled. Those are NOT inserted into the
    weeks, so week percentages and the overall figure are untouched and a
    signed-off week cannot reopen.
    """
    edits = (overlay_for_module or {}).get('edits', {}) or {}
    items = (overlay_for_module or {}).get('items', []) or []

    # 1. Edits and hides, applied by ID wherever the item lives.
    if edits:
        for container in _all_containers(curriculum):
            for i in range(len(container) - 1, -1, -1):
                item = container[i]
                if not isinstance(item, dict):
                    continue
                edit = edits.get(item.get('id'))
                if not edit:
                    continue
                if edit.get('hidden'):
                    # Removed from view, never deleted: a trainee who already
                    # completed it keeps that history, and their week can only
                    # go up as the denominator shrinks.
                    container.pop(i)
                    continue
                for key, value in (edit.get('fields') or {}).items():
                    item[key] = value

    # 2. Additions — in place, or into the appended bucket.
    added_since = []
    for row in sorted(items, key=lambda r: (r.get('sort_order') or 0, r.get('item_id') or '')):
        published_at = row.get('published_at')
        item = dict(row.get('payload') or {})
        item['id'] = row['item_id']
        if edits.get(item['id'], {}).get('hidden'):
            continue
        for key, value in (edits.get(item['id'], {}).get('fields') or {}).items():
            item[key] = value

        started_before_this = (
            enrolled_at is not None
            and published_at is not None
            and published_at > enrolled_at
        )
        container = _target_container(curriculum, row.get('target') or {})
        if started_before_this or container is None:
            entry = dict(item)
            entry['_target'] = row.get('target') or {}
            entry['_unplaceable'] = container is None
            added_since.append(entry)
        else:
            container.append(item)

    return curriculum, added_since


def added_since_item_ids(added_since):
    """IDs in the appended bucket.

    Their own progress bucket — deliberately absent from
    ``get_all_item_ids()``, which is what week percentages and the overall
    figure divide by.
    """
    return [i['id'] for i in (added_since or []) if i.get('id')]
